In [1]:
import requests
import pandas as pd
import re
import numpy as np

In [2]:
pd.set_option('display.max_rows', 2500)
pd.set_option('display.max_columns', 500)

In [3]:
headers = {
    'sec-ch-ua-platform': '"macOS"',
    'Referer': 'https://e-katanalotis.gov.gr/',
    'Accept-Language': 'en-US,en;q=0.9',
    'Accept': 'application/json, text/javascript, */*; q=0.01',
    'sec-ch-ua': '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
    'sec-ch-ua-mobile': '?0',
}

params = {
    'cid': '1730332800000',
}

response = requests.get(
    'https://warply.s3.amazonaws.com/applications/ed840ad545884deeb6c6b699176797ed/basket-retailers/prices.json',
    params=params,
    headers=headers,
)

In [4]:
data = response.json()

In [5]:
prod = data['context']['MAPP_PRODUCTS']['result']['products']

In [6]:
merchants = data['context']['MAPP_PRODUCTS']['result']['merchants']

In [7]:
def get_merchants(uuid:int):
    merchant = 'not found'
    for item in merchants:
        if item['merchant_uuid']==uuid:
            merchant = item['name']
            break
    return merchant

In [8]:
suppliers = data['context']['MAPP_PRODUCTS']['result']['suppliers']

In [9]:
def get_supplier(uuid:int):
    supplier = 'not found'
    for item in suppliers:
        if item['id']==uuid:
            supplier = item['name']
            break
    return supplier

In [10]:
categories = data['context']['MAPP_PRODUCTS']['result']['categories']

In [11]:
categories[10]

{'name': 'Είδη μιας χρήσης & Είδη Πάρτι',
 'uuid': 163,
 'sub_categories': [{'name': 'Είδη Συντήρησης & Ψησίματος τροφίμων',
   'uuid': 164,
   'sub_sub_categories': [{'name': 'Λαδόχαρτα & Σακούλες ψησίματος',
     'uuid': 165},
    {'name': 'Αλουμινόχαρτα', 'uuid': 166},
    {'name': 'Σακούλες συντήρησης τροφίμων', 'uuid': 167}]},
  {'name': 'Σακούλες απορριμμάτων',
   'uuid': 168,
   'sub_sub_categories': [{'name': 'Σακούλες απορριμμάτων', 'uuid': 169}]}]}

In [12]:
def category_long(category:dict):
    results=[]
    result={}
    result['name']=category['name']
    result['uuid']=category['uuid']
    results.append(result)
    for item in category['sub_categories']:
        result={}
        result['name']=item['name']
        result['uuid']=item['uuid']
        results.append(result)
        for sub_sub in item['sub_sub_categories']:
            result={}
            result['name']=sub_sub['name']
            result['uuid']=sub_sub['uuid']
            results.append(result)
    return results

In [13]:
def find_category(uuid:int):
    category = 'Not found'
    for item in category_results:
        if item['uuid']==uuid:
            category = item['name']
    return category

In [14]:
category_results=[]
for item in categories:
    category_results = category_results+category_long(item)

In [15]:
def category_df(record:dict):
    results = []
    
    
    if record['sub_categories']:
        subcategories = record['sub_categories']
        
        if isinstance(subcategories, list) and len(subcategories)>0:
            for i, item in enumerate(subcategories):
                
                if item['sub_sub_categories'] and isinstance(item['sub_sub_categories'], list) and len(item['sub_sub_categories'])>0:
                    for n, sub_sub_item in enumerate(item['sub_sub_categories']):
                        result = {}
                        result['name'] = record['name']
                        result['uuid'] = record['uuid']
                        
                        result[f"sub_name"]=item['name']
                        result[f"sub_uuid"]=item['uuid']
                        
                        
                        result[f"sub_sub_name"]=sub_sub_item['name']
                        result[f"sub_sub_uuid"]=sub_sub_item['uuid']
                        results.append(result)

    return results

# record(categories[1])

In [16]:
results = []
for item in categories:
    results=results+category_df(item)

In [17]:
cat = pd.DataFrame(results)

In [18]:
cat

,name,uuid,sub_name,sub_uuid,sub_sub_name,sub_sub_uuid
0,Έτοιμα Γεύματα,1,Λαδερά,2,Λαδερά,3
1,Αλλαντικά,4,Αλλαντικά Γαλοπούλας & Κοτόπουλου,5,Αλλαντικά Γαλοπούλας,6
2,Αλλαντικά,4,Αλλαντικά Γαλοπούλας & Κοτόπουλου,5,Αλλαντικά Κοτόπουλου,7
3,Αλλαντικά,4,"Ζαμπόν, Μπέικον & Ωμοπλάτη",8,Ζαμπόν Μπούτι,9
4,Αλλαντικά,4,"Ζαμπόν, Μπέικον & Ωμοπλάτη",8,Προσούτο & Jamon,10
5,Αλλαντικά,4,"Ζαμπόν, Μπέικον & Ωμοπλάτη",8,"Μπέικον, Ωμοπλάτη & Μπριζόλα",11
6,Αλλαντικά,4,Λουκάνικα,12,Χωριάτικα Λουκάνικα,13
7,Αλλαντικά,4,Λουκάνικα,12,Λουκάνικα Κοκτέιλ,14
8,Αλλαντικά,4,Λουκάνικα,12,Λουκάνικα Φρανκφούρτης,15
9,Αλλαντικά,4,Πάριζα & Μορταδέλα,16,Μορταδέλα,17
10,Αλλαντικά,4,Πάριζα & Μορταδέλα,16,Πάριζα,18
11,Αλλαντικά,4,Σαλάμια,19,Σαλάμια αέρος Χοιρινά & Μοσχαρίσια,20
12,"Αναψυκτικά, Νερά & Χυμοί",21,"Αναψυκτικά, Σόδες & Ενεργειακά ποτά",22,Ice Tea & Ice Coffee,23
13,"Αναψυκτικά, Νερά & Χυμοί",21,"Αναψυκτικά, Σόδες & Ενεργειακά ποτά",22,"Σόδες, Τόνικ & Mixers",24
14,"Αναψυκτικά, Νερά & Χυμοί",21,"Αναψυκτικά, Σόδες & Ενεργειακά ποτά",22,Πορτοκαλάδες,25
15,"Αναψυκτικά, Νερά & Χυμοί",21,"Αναψυκτικά, Σόδες & Ενεργειακά ποτά",22,Cola,26
16,"Αναψυκτικά, Νερά & Χυμοί",21,"Αναψυκτικά, Σόδες & Ενεργειακά ποτά",22,Λεμονάδες & Γκαζόζες,27
17,"Αναψυκτικά, Νερά & Χυμοί",21,"Αναψυκτικά, Σόδες & Ενεργειακά ποτά",22,Ενεργειακά & Ισοτονικά ποτά,28
18,"Αναψυκτικά, Νερά & Χυμοί",21,Νερά,29,Ανθρακούχα νερά,30
19,"Αναψυκτικά, Νερά & Χυμοί",21,Νερά,29,Φυσικά Μεταλλικά & Επιτραπέζια νερά,31
20,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,Χυμοί Πορτοκάλι & άλλα Εσπεριδοειδή,33
21,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,Χυμοί ψυγείου Ανάμικτοι,34
22,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,Παιδικοί Χυμοί,35
23,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,Χυμοί Βύσσινο,36
24,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,"Χυμοί Μήλο, Ρόδι & άλλες γεύσεις",37
25,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,Χυμοί Ροδάκινο,38
26,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,Χυμοί ψυγείου Πορτοκάλι & άλλα Εσπεριδοειδή,39
27,"Αναψυκτικά, Νερά & Χυμοί",21,Χυμοί,32,Ανάμικτοι χυμοί,40
28,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά πιάτων,42,Απορρυπαντικά πιάτων για πλύσιμο στο χέρι,43
29,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά πιάτων,42,Απορρυπαντικά πιάτων πλυντηρίου,44
30,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά πιάτων,42,Συμπληρωματικά πλυντηρίου πιάτων,45
31,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,Απορρυπαντικά ρούχων υγρά,47
32,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,Μαλακτικά ρούχων & Ενισχυτικά αρώματος,48
33,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,Απορρυπαντικά ρούχων σε σκόνη,49
34,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,Απορρυπαντικά ρούχων σε κάψουλες,50
35,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,Αποσκληρυντικά νερού,51
36,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,"Χρωμοπαγίδες, Λευκαντικά & Ενισχυτικά πλυσίματος",52
37,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,Απολυμαντικά ρούχων,53
38,Απορρυπαντικά & Είδη Καθαρισμού,41,Απορρυπαντικά ρούχων,46,Απορρυπαντικά παιδικών ρούχων,54
39,Απορρυπαντικά & Είδη Καθαρισμού,41,Καθαριστικά γενικής χρήσης,55,Αποφρακτικά & Αποφρακτήρες,56
40,Απορρυπαντικά & Είδη Καθαρισμού,41,Καθαριστικά γενικής χρήσης,55,Καθαριστικά για όλες τις επιφάνειες,57
41,Απορρυπαντικά & Είδη Καθαρισμού,41,Καθαριστικά γενικής χρήσης,55,Χλωρίνες & Χλωροκαθαριστικά,58
42,Απορρυπαντικά & Είδη Καθαρισμού,41,Καθαριστικά γενικής χρήσης,55,Καθαριστικά τουαλέτας,59
43,Απορρυπαντικά & Είδη Καθαρισμού,41,Καθαριστικά γενικής χρήσης,55,Καθαριστικά τζαμιών,60
44,Απορρυπαντικά & Είδη Καθαρισμού,41,Καθαριστικά γενικής χρήσης,55,Καθαριστικά πατώματος,61
45,Απορρυπαντικά & Είδη Καθαρισμού,41,Σύνεργα καθαρισμού,62,Σφουγγαρίστρες & Κουβάδες,63
46,Απορρυπαντικά & Είδη Καθαρισμού,41,Σύνεργα καθαρισμού,62,"Σφουγγαράκια, Σύρματα & Βούρτσες",64
47,Απορρυπαντικά & Είδη Καθαρισμού,41,Σύνεργα καθαρισμού,62,Σπογγοπετσέτες (τύπου Wettex),65
48,Απορρυπαντικά & Είδη Καθαρισμού,41,Σύνεργα καθαρισμού,62,Γάντια,66
49,Απορρυπαντικά & Είδη Καθαρισμού,41,Σύνεργα καθαρισμού,62,Σκούπες & Φαράσια,67
50,"Αυγά, Βούτυρο, Νωπές Ζύμες & Ζωμοί",68,Αυγά,69,Ασπράδια αυγού,70
51,"Αυγά, Βούτυρο, Νωπές Ζύμες & Ζωμοί",68,Αυγά,69,Αυγά,71
52,"Αυγά, Βούτυρο, Νωπές Ζύμες & Ζωμοί",68,Βούτυρα,72,Βούτυρο γάλακτος,73
53,"Αυγά, Βούτυρο, Νωπές Ζύμες & Ζωμοί",68,Βούτυρα,72,Βούτυρα Αγελάδος & Πρόβεια,74
54,"Αυγά, Βούτυρο, Νωπές Ζύμες & Ζωμοί",68,Μαργαρίνες,75,Μαργαρίνες,76
55,Βρεφικές & Παιδικές τροφές,77,Βρεφικά & Παιδικά γάλατα,78,Γάλατα σκόνη 1ης Βρεφικής ηλικίας,79
56,Βρεφικές & Παιδικές τροφές,77,Βρεφικά & Παιδικά γάλατα,78,Γάλατα σκόνη 2ης Βρεφικής ηλικίας,80
57,Βρεφικές & Παιδικές τροφές,77,Βρεφικά & Παιδικά γάλατα,78,Γάλατα σκόνη 3ης Βρεφικής ηλικίας,81
58,Βρεφικές & Παιδικές τροφές,77,Βρεφικές & Παιδικές κρέμες,82,Παιδικά ροφήματα,83
59,Βρεφικές & Παιδικές τροφές,77,Βρεφικές & Παιδικές κρέμες,82,Παιδικές κρέμες Μπισκότο,84
60,Βρεφικές & Παιδικές τροφές,77,Βρεφικές & Παιδικές κρέμες,82,Φρουτόκρεμες έτοιμες,85
61,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Γάλατα Σοκολατούχα ψυγείου,87,Γάλατα Σοκολατούχα υψηλής παστερίωσης,88
62,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Γάλατα Σοκολατούχα ψυγείου,87,Γάλατα Σοκολατούχα φρέσκα,89
63,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Γάλατα ψυγείου,90,Γάλατα Αγελάδος υψηλής παστερίωσης,91
64,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Γάλατα ψυγείου,90,Γάλατα Αγελάδος φρέσκα,92
65,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Γάλατα ψυγείου,90,"Ξυνόγαλα, Κεφίρ & Αριάνι",93
66,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Γάλατα ψυγείου,90,Γάλατα Κατσικίσια & Πρόβεια υψηλής παστερίωσης,94
67,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Γάλατα ψυγείου,90,Γάλατα Kατσικίσια & Πρόβεια φρέσκα,95
68,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Φυτικά & Άλλα ροφήματα Ψυγείου,96,"Φυτικά ροφήματα Σόγιας, Καρύδας & άλλες γεύσεις",97
69,"Γάλατα, Ροφήματα & Χυμοί ψυγείου",86,Φυτικά & Άλλα ροφήματα Ψυγείου,96,Φυτικά ροφήματα Αμυγδάλου,98
70,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Γιαούρτια Κατσικίσια & Πρόβεια,101
71,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Γιαούρτια Αγελάδος στραγγιστά,102
72,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,"Κρέμες Βανίλιας, Σοκολάτας, Καραμελέ & άλλα Επ...",103
73,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Παιδικά γιαούρτια με Μπισκότο,104
74,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Ρυζόγαλα,105
75,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Ζελέ & Μουσταλευριά,106
76,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,"Επιδόρπια γιαουρτιού με Ανανά, Κεράσι & Φράουλα",107
77,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Παιδικά γιαούρτια με Φράουλα,108
78,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Πρωτεϊνούχα & Λειτουργικά ροφήματα,109
79,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Επιδόρπια γιαουρτιού με Ροδάκινο & Βερίκοκο,110
80,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Γιαούρτια Αγελάδος,111
81,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Βρεφικά γιαούρτια,112
82,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Επιδόρπια γιαουρτιού με Εσπεριδοειδή,113
83,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Επιδόρπια με Μέλι & άλλες γεύσεις,114
84,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Επιδόρπια γιαουρτιού με Δημητριακά,115
85,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Παιδικά γιαούρτια με Μπανάνα,116
86,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια,100,Γαλακτοφέτες,117
87,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια Βρεφικά & Παιδικά,118,Βρεφικά γιαούρτια,119
88,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Γιαούρτια Βρεφικά & Παιδικά,118,Παιδικά γιαούρτια με Μπανάνα,120
89,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Επιδόρπια γιαουρτιού,121,"Επιδόρπια γιαουρτιού με Ανανά, Κεράσι & Φράουλα",122
90,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Κρέμες γάλακτος & Σαντιγί,123,Φυτικές κρέμες,124
91,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Κρέμες γάλακτος & Σαντιγί,123,Κρέμες γάλακτος,125
92,"Γιαούρτια, Κρέμες γάλακτος & Επιδόρπια ψυγείου",99,Ρυζόγαλα & Γλυκίσματα ψυγείου,126,"Κρέμες Βανίλιας, Σοκολάτας, Καραμελέ & άλλα Επ...",127
93,Είδη Αρτοζαχαροπλαστείου,128,"Κέικ, Τσουρέκια & Κρουασάν",129,Τσουρέκι,130
94,Είδη Αρτοζαχαροπλαστείου,128,"Κέικ, Τσουρέκια & Κρουασάν",129,Κέικ,131
95,Είδη Αρτοζαχαροπλαστείου,128,"Κέικ, Τσουρέκια & Κρουασάν",129,Κρουασάν,132
96,Είδη Αρτοζαχαροπλαστείου,128,"Κέικ, Τσουρέκια & Κρουασάν",129,"Donuts, Στρούντελ & Λουκουμάδες",133
97,Είδη Αρτοζαχαροπλαστείου,128,Κουλούρια & Βουτήματα,134,Κουλούρια,135
98,Είδη Αρτοζαχαροπλαστείου,128,"Κριτσίνια, Παξιμάδια & Φρυγανιές",136,Παξιμάδια,137
99,Είδη Αρτοζαχαροπλαστείου,128,"Κριτσίνια, Παξιμάδια & Φρυγανιές",136,Κριτσίνια,138
100,Είδη Αρτοζαχαροπλαστείου,128,"Κριτσίνια, Παξιμάδια & Φρυγανιές",136,Φρυγανιές & Κρουτόν,139
101,Είδη Αρτοζαχαροπλαστείου,128,Πίτες & Τορτίγιες,140,Αραβικές πίτες,141
102,Είδη Αρτοζαχαροπλαστείου,128,Πίτες & Τορτίγιες,140,Βάση πίτσας,142
103,Είδη Αρτοζαχαροπλαστείου,128,Πίτες & Τορτίγιες,140,Πίτες για Σουβλάκια,143
104,Είδη Αρτοζαχαροπλαστείου,128,Πίτες & Τορτίγιες,140,Κυπριακές πίτες,144
105,Είδη Αρτοζαχαροπλαστείου,128,Πίτες & Τορτίγιες,140,Μεξικάνικες πίτες,145
106,Είδη Αρτοζαχαροπλαστείου,128,Ψωμί & Αρτοσκευάσματα,146,"Μπαγκέτα, Μαργαρίτα & άλλα Ψωμιά για σάντουιτς",147
107,Είδη Αρτοζαχαροπλαστείου,128,Ψωμί τυποποιημένο,148,"Ψωμί Ζέας, Chia & άλλες γεύσεις για τοστ",149
108,Είδη Αρτοζαχαροπλαστείου,128,Ψωμί τυποποιημένο,148,Ψωμί για τοστ σίτου,150
109,Είδη Αρτοζαχαροπλαστείου,128,Ψωμί τυποποιημένο,148,Ψωμί για τοστ σίκαλης & ολικής,151
110,Είδη Αρτοζαχαροπλαστείου,128,Ψωμί τυποποιημένο,148,Ψωμί για τοστ πολύσπορο,152
111,Είδη Αρτοζαχαροπλαστείου,128,Ψωμί τυποποιημένο,148,Ψωμί για σάντουιτς,153
112,Είδη Οικιακής χρήσης,154,Είδη Σιδερώματος & Απλώματος,155,Υγρά & Κόλλες σιδερώματος,156
113,Είδη Οικιακής χρήσης,154,"Είδη Υγραερίου, Αναπτήρες & Σπίρτα",157,Φιαλίδια & Συσκευές υγραερίου,158
114,Είδη Οικιακής χρήσης,154,Εντομοαπωθητικά & Εντομοκτόνα,159,Εντομοκτόνα,160
115,Είδη Οικιακής χρήσης,154,"Μπαταρίες, Λάμπες, Ηλεκτρολογικά είδη & Ταινίες",161,Μπαταρίες,162
116,Είδη μιας χρήσης & Είδη Πάρτι,163,Είδη Συντήρησης & Ψησίματος τροφίμων,164,Λαδόχαρτα & Σακούλες ψησίματος,165
117,Είδη μιας χρήσης & Είδη Πάρτι,163,Είδη Συντήρησης & Ψησίματος τροφίμων,164,Αλουμινόχαρτα,166
118,Είδη μιας χρήσης & Είδη Πάρτι,163,Είδη Συντήρησης & Ψησίματος τροφίμων,164,Σακούλες συντήρησης τροφίμων,167
119,Είδη μιας χρήσης & Είδη Πάρτι,163,Σακούλες απορριμμάτων,168,Σακούλες απορριμμάτων,169
120,Είδη πρωινού & Ροφήματα,170,Γάλατα & Φυτικά ροφήματα Μακράς διαρκείας,171,Γάλατα Συμπυκνωμένα,172
121,Είδη πρωινού & Ροφήματα,170,Γάλατα & Φυτικά ροφήματα Μακράς διαρκείας,171,Γάλατα Ζαχαρούχα,173
122,Είδη πρωινού & Ροφήματα,170,Δημητριακά & Μπάρες δημητριακών,174,Μπάρες δημητριακών & Ξηρών καρπών,175
123,Είδη πρωινού & Ροφήματα,170,Δημητριακά & Μπάρες δημητριακών,174,Δημητριακά Βρόμης & Muesli,176
124,Είδη πρωινού & Ροφήματα,170,Δημητριακά & Μπάρες δημητριακών,174,Δημητριακά Corn Flakes,177
125,Είδη πρωινού & Ροφήματα,170,Δημητριακά & Μπάρες δημητριακών,174,Δημητριακά Bran & Διαίτης,178
126,Είδη πρωινού & Ροφήματα,170,Δημητριακά & Μπάρες δημητριακών,174,Παιδικά δημητριακά,179
127,Είδη πρωινού & Ροφήματα,170,Δημητριακά & Μπάρες δημητριακών,174,Ρυζογκοφρέτες,180
128,Είδη πρωινού & Ροφήματα,170,"Καφέδες, Ροφήματα & Αφεψήματα",181,"Κακάο, Σοκολάτα & άλλα ροφήματα",182
129,Είδη πρωινού & Ροφήματα,170,"Καφέδες, Ροφήματα & Αφεψήματα",181,Καφέδες Espresso,183
130,Είδη πρωινού & Ροφήματα,170,"Καφέδες, Ροφήματα & Αφεψήματα",181,Καφέδες Στιγμής,184
131,Είδη πρωινού & Ροφήματα,170,"Καφέδες, Ροφήματα & Αφεψήματα",181,Καφέδες Φίλτρου,185
132,Είδη πρωινού & Ροφήματα,170,"Καφέδες, Ροφήματα & Αφεψήματα",181,Καφέδες Ελληνικοί,186
133,Είδη πρωινού & Ροφήματα,170,"Καφέδες, Ροφήματα & Αφεψήματα",181,Τσάι,187
134,Είδη πρωινού & Ροφήματα,170,Μέλια & Μαρμελάδες,188,Μέλια,189
135,Είδη πρωινού & Ροφήματα,170,Μέλια & Μαρμελάδες,188,Μαρμελάδες,190
136,Είδη πρωινού & Ροφήματα,170,"Πραλίνες, Ταχίνι & Φιστικοβούτυρο",191,Πραλίνες αλειφόμενες,192
137,Είδη πρωινού & Ροφήματα,170,"Πραλίνες, Ταχίνι & Φιστικοβούτυρο",191,Ταχίνι,193
138,Είδη πρωινού & Ροφήματα,170,"Πραλίνες, Ταχίνι & Φιστικοβούτυρο",191,Φιστικοβούτυρο,194
139,Κάβα,195,Ποτά,196,Έτοιμα Κοκτέιλ,197
140,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Βρεφικά & Παιδικά καλλυντικά,199,"Βρεφικές & Παιδικές Πούδρες, Λάδια & Κολόνιες",200
141,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Βρεφικά & Παιδικά καλλυντικά,199,Παιδική Στοματική υγιεινή,201
142,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Είδη Ξυρίσματος & After Shave,202,Ξυραφάκια μιας χρήσης,203
143,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Είδη Ξυρίσματος & After Shave,202,Ξυριστικές μηχανές & Ανταλλακτικά,204
144,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Είδη Ξυρίσματος & After Shave,202,Αποτριχωτικά,205
145,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Είδη Ξυρίσματος & After Shave,202,After Shave,206
146,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Παραφαρμακευτικά Είδη,207,"Αντισηπτικά Υγρά, Μαντιλάκια & Μάσκες",208
147,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Παραφαρμακευτικά Είδη,207,Προφυλακτικά,209
148,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Παραφαρμακευτικά Είδη,207,Ωτοκαθαριστές,210
149,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Παραφαρμακευτικά Είδη,207,Επίδεσμοι & Επιθέματα,211
150,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Παραφαρμακευτικά Είδη,207,Βαμβάκι,212
151,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Στοματική υγιεινή,213,Φθοριούχα διαλύματα δοντιών,214
152,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Στοματική υγιεινή,213,Οδοντόβουρτσες & Οδοντικά νήματα,215
153,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Στοματική υγιεινή,213,Οδοντόκρεμες & Γυαλιστικά δοντιών,216
154,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Υγιεινή & Περιποίηση Προσώπου,217,Δίσκοι ντεμακιγιάζ,218
155,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Υγιεινή & Περιποίηση Προσώπου,217,Κρέμες & Μάσκες περιποίησης προσώπου,219
156,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Υγιεινή & Περιποίηση Προσώπου,217,Ενυδάτωση Χειλιών,220
157,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Μαλλιών,221,Μάσκες & Λάδια για τα μαλλιά,222
158,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Μαλλιών,221,Μαλακτικές κρέμες μαλλιών,223
159,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Μαλλιών,221,Σαμπουάν,224
160,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Μαλλιών,221,Λακ μαλλιών,225
161,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Σώματος,226,"Αφρόλουτρα, Ντους & Άλατα μπάνιου",227
162,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Σώματος,226,Σαπούνια & Υγροσάπουνα,228
163,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Σώματος,226,Αποσμητικά σώματος,229
164,Καλλυντικά & Είδη Προσωπικής υγιεινής,198,Φροντίδα Σώματος,226,Γαλακτώματα & Λάδια σώματος,230
165,Κατεψυγμένα,231,Κατεψυγμένα Γεύματα,232,Κατεψυγμένα γεύματα με Λαχανικά & άλλα κατεψυγ...,233
166,Κατεψυγμένα,231,Κατεψυγμένα Κρέατα & Πουλερικά,234,Παρασκευάσματα κρεάτων κατεψυγμένα,235
167,Κατεψυγμένα,231,Κατεψυγμένα Κρέατα & Πουλερικά,234,Παρασκευάσματα πουλερικών κατεψυγμένα,236
168,Κατεψυγμένα,231,Κατεψυγμένα Λαχανικά & Φρούτα,237,Λαχανικά κατεψυγμένα,238
169,Κατεψυγμένα,231,Κατεψυγμένα Λαχανικά & Φρούτα,237,Πατάτες κατεψυγμένες,239
170,Κατεψυγμένα,231,Κατεψυγμένα Ψάρια & Θαλασσινά,240,Ψάρια κατεψυγμένα,241
171,Κατεψυγμένα,231,Κατεψυγμένα Ψάρια & Θαλασσινά,240,Οστρακοειδή κατεψυγμένα,242
172,Κατεψυγμένα,231,Κατεψυγμένα Ψάρια & Θαλασσινά,240,"Χταπόδια, Καλαμάρια & Σουπιές κατεψυγμένα",243
173,Κατεψυγμένα,231,Κατεψυγμένα αναπληρώματα Κρέατος,244,Κατεψυγμένα αναπληρώματα κρέατος,245
174,Κατεψυγμένα,231,"Κατεψυγμένες Ζύμες, Πίτες & Πίτσες",246,Πίτες & Πιτάκια κατεψυγμένα,247
175,Κατεψυγμένα,231,"Κατεψυγμένες Ζύμες, Πίτες & Πίτσες",246,Πίτσες κατεψυγμένες,248
176,Κατεψυγμένα,231,"Κατεψυγμένες Ζύμες, Πίτες & Πίτσες",246,Ζύμες κατεψυγμένες,249
177,Κατεψυγμένα,231,Παγωτά & Παγάκια,250,Παγωτά Ατομικά & Μίνι,251
178,Κατεψυγμένα,231,Παγωτά & Παγάκια,250,Παγωτά Οικογενειακά,252
179,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Μπισκότα,254,"Μπισκότα Βουτύρου, Κανέλας & άλλες γεύσεις",255
180,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Μπισκότα,254,Μπισκότα Γεμιστά & με επικάλυψη σοκολάτας,256
181,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Μπισκότα,254,Μπισκότα τύπου Πτι Μπερ & Μιράντα,257
182,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Μπισκότα,254,Μπισκότα Digestive & Δημητριακών,258
183,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Μπισκότα,254,Μπισκότα Cookies,259
184,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Μπισκότα,254,Cream crackers,260
185,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Σοκολάτες,261,Σοκολάτες Γάλακτος & Λευκές,262
186,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Σοκολάτες,261,Σοκολάτες Υγείας,263
187,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Σοκολάτες,261,Σοκολατάκια,264
188,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Σοκολάτες,261,Γκοφρέτες & Πουράκια,265
189,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,Σοκολάτες,261,Κουβερτούρες,266
190,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,"Τσίχλες, Καραμέλες & Γλειφιτζούρια",267,Καραμέλες,268
191,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,"Τσίχλες, Καραμέλες & Γλειφιτζούρια",267,Τσίχλες,269
192,"Μπισκότα, Σοκολάτες & Ζαχαρώδη",253,"Τσίχλες, Καραμέλες & Γλειφιτζούρια",267,Γλειφιτζούρια,270
193,Ξηροί Καρποί & Σνακ,271,Ξηροί καρποί & Αποξηραμένα φρούτα,272,Cranberries & άλλα Super Fruits αποξηραμένα,273
194,Ξηροί Καρποί & Σνακ,271,Ξηροί καρποί & Αποξηραμένα φρούτα,272,"Δαμάσκηνα, Σύκα & Χουρμάδες αποξηραμένα",274
195,Ξηροί Καρποί & Σνακ,271,Ξηροί καρποί & Αποξηραμένα φρούτα,272,Βερίκοκα & άλλα αποξηραμένα φρούτα,275
196,Ξηροί Καρποί & Σνακ,271,"Πατατάκια, Γαριδάκια & άλλα Σνακ",276,Νάτσος,277
197,Ξηροί Καρποί & Σνακ,271,"Πατατάκια, Γαριδάκια & άλλα Σνακ",276,Ποπ Κορν,278
198,Ξηροί Καρποί & Σνακ,271,"Πατατάκια, Γαριδάκια & άλλα Σνακ",276,Γαριδάκια & άλλα Σνακ,279
199,Ξηροί Καρποί & Σνακ,271,"Πατατάκια, Γαριδάκια & άλλα Σνακ",276,Πατατάκια,280
200,Ορεκτικά & Delicatessen,281,Σαλάτες & Αλοιφές,282,Ρώσικη σαλάτα,283
201,Ορεκτικά & Delicatessen,281,Σαλάτες & Αλοιφές,282,Τυροκαυτερή & Τυροσαλάτα,284
202,Ορεκτικά & Delicatessen,281,Σαλάτες & Αλοιφές,282,Τζατζίκι & Σκορδαλιά,285
203,Ορεκτικά & Delicatessen,281,Σαλάτες & Αλοιφές,282,Σαλάτα Κηπουρού & άλλες σαλάτες,286
204,Ορεκτικά & Delicatessen,281,Σαλάτες & Αλοιφές,282,Χούμους,287
205,Ορεκτικά & Delicatessen,281,Χαλβάδες,288,Χαλβάς Βανίλια,289
206,Ορεκτικά & Delicatessen,281,Χαλβάδες,288,Χαλβάς Κακάο,290
207,Ορεκτικά & Delicatessen,281,Χαλβάδες,288,Χαλβάς Αμύγδαλο,291
208,Τροφές & Είδη για Κατοικίδια,292,Τροφές & Είδη για Γάτες,293,Ξηρά τροφή Γάτας,294
209,Τροφές & Είδη για Κατοικίδια,292,Τροφές & Είδη για Γάτες,293,Υγρή τροφή Γάτας,295
210,Τροφές & Είδη για Κατοικίδια,292,Τροφές & Είδη για Γάτες,293,Σνακ Γάτας,296
211,Τροφές & Είδη για Κατοικίδια,292,Τροφές & Είδη για Σκύλους,297,Σνακ Σκύλου,298
212,Τροφές & Είδη για Κατοικίδια,292,Τροφές & Είδη για Σκύλους,297,Υγρή τροφή Σκύλου,299
213,Τρόφιμα Παντοπωλείου,300,Όσπρια,301,"Ρεβίθια, Φάβα & άλλα Όσπρια",302
214,Τρόφιμα Παντοπωλείου,300,Όσπρια,301,Φασόλια,303
215,Τρόφιμα Παντοπωλείου,300,Όσπρια,301,Φακές,304
216,Τρόφιμα Παντοπωλείου,300,Αλεύρι & Σιμιγδάλι,305,Σιμιγδάλι,306
217,Τρόφιμα Παντοπωλείου,300,Αλεύρι & Σιμιγδάλι,305,Αλεύρι,307
218,Τρόφιμα Παντοπωλείου,300,Ζάχαρη & Υποκατάστατα ζάχαρης,308,Ζάχαρη Μαύρη & Καστανή,309
219,Τρόφιμα Παντοπωλείου,300,Ζάχαρη & Υποκατάστατα ζάχαρης,308,Ζάχαρη Λευκή,310
220,Τρόφιμα Παντοπωλείου,300,Ζάχαρη & Υποκατάστατα ζάχαρης,308,Υποκατάστατα ζάχαρης,311
221,Τρόφιμα Παντοπωλείου,300,Ζυμαρικά,312,Μακαρόνια,313
222,Τρόφιμα Παντοπωλείου,300,Ζυμαρικά,312,"Πένες, Τορτελίνι, Κριθαράκι & άλλες Πάστες",314
223,Τρόφιμα Παντοπωλείου,300,Ζυμαρικά,312,Παραδοσιακά ζυμαρικά,315

In [19]:
import json

In [20]:
def product(record:dict):
    results=[]
    fields = json.loads(record['extra_fields'])
    for item in record['prices']:
        result ={}
        result['product_id']=record['barcode']
        result['name'] = record['name']
        
        result['date'] = fields['date']
        result['unit'] = fields['unit']
        
        if isinstance(record['category'], list):
            categories = ', '.join([find_category(i) for i in record['category']])
            result['category_name'] = categories
        
        result['category_codes'] = record['category']
        
        result['monimi_meiosi'] = record['monimi_meiosi']
        result['promo'] = record['promo']
        
        result['supplier_name'] = get_supplier(record['supplier'])
        result['supplier_code'] = record['supplier']
        
        result['merchant'] = get_merchants(int(item['merchant_uuid']))
        result['price'] = item['price']
        
        results.append(result)
    return results

In [21]:
results_products = []
for item in prod:
    results_products= results_products + product(item)

In [22]:
df = pd.DataFrame(results_products)

In [23]:
df.tail()

,product_id,name,date,unit,category_name,category_codes,monimi_meiosi,promo,supplier_name,supplier_code,merchant,price
24959,904,ΣΟΛΟΜΟΣ ΦΙΛΕΤΟ Μ/Δ ΝΩΠΟ 4/250G,29-10-2024,ανά κιλ,"Φρέσκο Ψάρι & Θαλασσινά, Ψάρια Ιχθυοκαλλιέργει...","[424, 425, 428]",False,False,Ν/Α,302.0,xalkiadakis,34.90
24960,9066001427506,ALPILAND ESPRESSO 250ML,29-10-2024,ανά κιλ,"Αναψυκτικά, Νερά & Χυμοί, Αναψυκτικά, Σόδες & ...","[21, 22, 23]",True,False,ALPILAND,46.0,mymarket,1.20
24961,9066001427506,ALPILAND ESPRESSO 250ML,29-10-2024,ανά κιλ,"Αναψυκτικά, Νερά & Χυμοί, Αναψυκτικά, Σόδες & ...","[21, 22, 23]",True,False,ALPILAND,46.0,ab,1.12
24962,9066001427605,ALPILAND CAPPUCCINO 250ML,29-10-2024,ανά κιλ,"Αναψυκτικά, Νερά & Χυμοί, Αναψυκτικά, Σόδες & ...","[21, 22, 23]",True,False,ALPILAND,46.0,mymarket,1.20
24963,9066001427605,ALPILAND CAPPUCCINO 250ML,29-10-2024,ανά κιλ,"Αναψυκτικά, Νερά & Χυμοί, Αναψυκτικά, Σόδες & ...","[21, 22, 23]",True,False,ALPILAND,46.0,ab,1.12

In [24]:
#!/usr/bin/env python
# coding: utf-8

# Εισαγωγή των απαραίτητων βιβλιοθηκών
import requests
import pandas as pd
import re
import numpy as np
import json
from datetime import datetime
today = datetime.today().strftime('_%-d_%-m_%Y')

# Ρυθμίσεις για την εμφάνιση δεδομένων στο pandas
pd.set_option('display.max_rows', 2500)     # Ορισμός μέγιστου αριθμού γραμμών που θα εμφανίζονται
pd.set_option('display.max_columns', 500)   # Ορισμός μέγιστου αριθμού στηλών που θα εμφανίζονται

# Ορισμός των headers για το HTTP αίτημα
headers = {
    'sec-ch-ua-platform': '"macOS"',
    'Referer': 'https://e-katanalotis.gov.gr/',
    'Accept-Language': 'en-US,en;q=0.9',
    'Accept': 'application/json, text/javascript, */*; q=0.01',
    'sec-ch-ua': '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
    'sec-ch-ua-mobile': '?0',
}

params = {
    'cid': '1730332800000',
}

response = requests.get(
    'https://warply.s3.amazonaws.com/applications/ed840ad545884deeb6c6b699176797ed/basket-retailers/prices.json',
    params=params,
    headers=headers,
)

# Ανάγνωση της απόκρισης ως JSON
data = response.json()

# Ανάκτηση της λίστας των προϊόντων από τα δεδομένα
prod = data['context']['MAPP_PRODUCTS']['result']['products']

# Ανάκτηση της λίστας των εμπόρων από τα δεδομένα
merchants = data['context']['MAPP_PRODUCTS']['result']['merchants']

# Συνάρτηση για την εύρεση του ονόματος του εμπόρου με βάση το uuid
def get_merchants(uuid:int):
    merchant = 'not found'  # Αρχικοποίηση μεταβλητής
    for item in merchants:
        if item['merchant_uuid']==uuid:
            merchant = item['name']
            break
    return merchant

# Ανάκτηση της λίστας των προμηθευτών από τα δεδομένα
suppliers = data['context']['MAPP_PRODUCTS']['result']['suppliers']

# Συνάρτηση για την εύρεση του ονόματος του προμηθευτή με βάση το uuid
def get_supplier(uuid:int):
    supplier = 'not found'  # Αρχικοποίηση μεταβλητής
    for item in suppliers:
        if item['id']==uuid:
            supplier = item['name']
            break
    return supplier

# Ανάκτηση της λίστας των κατηγοριών από τα δεδομένα
categories = data['context']['MAPP_PRODUCTS']['result']['categories']

# Εμφάνιση της 11ης κατηγορίας (για έλεγχο)
categories[10]

# Συνάρτηση για την ανάπτυξη των κατηγοριών και υποκατηγοριών σε λίστα
def category_long(category:dict):
    results=[]
    result={}
    result['name']=category['name']
    result['uuid']=category['uuid']
    results.append(result)
    for item in category['sub_categories']:
        result={}
        result['name']=item['name']
        result['uuid']=item['uuid']
        results.append(result)
        for sub_sub in item['sub_sub_categories']:
            result={}
            result['name']=sub_sub['name']
            result['uuid']=sub_sub['uuid']
            results.append(result)
    return results

# Συνάρτηση για την εύρεση του ονόματος της κατηγορίας με βάση το uuid
def find_category(uuid:int):
    category = 'Not found'
    for item in category_results:
        if item['uuid']==uuid:
            category = item['name']
    return category

# Δημιουργία λίστας με όλα τα αποτελέσματα κατηγοριών
category_results=[]
for item in categories:
    category_results = category_results+category_long(item)

# Συνάρτηση για τη δημιουργία DataFrame από τις κατηγορίες
def category_df(record:dict):
    results = []
    if record['sub_categories']:
        subcategories = record['sub_categories']
        if isinstance(subcategories, list) and len(subcategories)>0:
            for i, item in enumerate(subcategories):
                if item['sub_sub_categories'] and isinstance(item['sub_sub_categories'], list) and len(item['sub_sub_categories'])>0:
                    for n, sub_sub_item in enumerate(item['sub_sub_categories']):
                        result = {}
                        result['name'] = record['name']
                        result['uuid'] = record['uuid']
                        result[f"sub_name"]=item['name']
                        result[f"sub_uuid"]=item['uuid']
                        result[f"sub_sub_name"]=sub_sub_item['name']
                        result[f"sub_sub_uuid"]=sub_sub_item['uuid']
                        results.append(result)
    return results

# Παράδειγμα εκτέλεσης της συνάρτησης (σχολιασμένο)
# record(categories[1])

# Συγκέντρωση όλων των αποτελεσμάτων σε μία λίστα
results = []
for item in categories:
    results=results+category_df(item)

# Δημιουργία DataFrame από τα αποτελέσματα των κατηγοριών
cat = pd.DataFrame(results)



# Συνάρτηση για την επεξεργασία των προϊόντων και τη δημιουργία λίστας λεξικών με τα δεδομένα
def product(record:dict):
    results=[]
    fields = json.loads(record['extra_fields'])  # Μετατροπή των 'extra_fields' από JSON string σε dict
    for item in record['prices']:
        result ={}
        result['product_id']=record['barcode']
        result['name'] = record['name']
        result['date'] = fields['date']
        result['unit'] = fields['unit']
        if isinstance(record['category'], list):
            categories = ', '.join([find_category(i) for i in record['category']])
            result['category_name'] = categories
        result['category_codes'] = record['category']
        result['monimi_meiosi'] = record['monimi_meiosi']
        result['promo'] = record['promo']
        result['supplier_name'] = get_supplier(record['supplier'])
        result['supplier_code'] = record['supplier']
        result['merchant'] = get_merchants(int(item['merchant_uuid']))
        result['price'] = item['price']
        results.append(result)
    return results

# Συγκέντρωση όλων των αποτελεσμάτων προϊόντων σε μία λίστα
results_products = []
for item in prod:
    results_products= results_products + product(item)

# Δημιουργία DataFrame από τα αποτελέσματα των προϊόντων
df = pd.DataFrame(results_products)
df.to_csv(f"data{today}.csv", index=False)

## Καλάθι οπωροκηπευτικών

In [26]:
response_3 = requests.get(
    'https://warply.s3.amazonaws.com/applications/ed840ad545884deeb6c6b699176797ed/basket-retailers/freshbasket.json?v=1730710976905',
    headers={
        'Accept': 'application/json, text/javascript, */*; q=0.01',
        'Accept-Language': 'en-US,en;q=0.9,el;q=0.8',
        'Connection': 'keep-alive',
        'Origin': 'https://e-katanalotis.gov.gr',
        'Referer': 'https://e-katanalotis.gov.gr/',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'cross-site',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
        'sec-ch-ua': '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"macOS"',
    }
)

In [28]:
data = response_3.json()

In [35]:
retailers = data['retailers'].keys()

In [66]:
from_date_object = datetime.strptime(data['from'], '%d-%m-%Y')
to_date_object = datetime.strptime(data['to'], '%d-%m-%Y')
filename = f"fresh_basket_{str(from_date_object.day)}_{str(from_date_object.month)}_to_{str(to_date_object.day)}_{str(to_date_object.month)}_{str(to_date_object.year)}.csv"

In [54]:
fresh_basket=[]
for retail in retailers:
    for i in data['retailers'][retail]['basket']:
        i['retailer'] = retail
        i['from'] = data['from']
        i['to'] = data['to']
        fresh_basket.append(i)

In [80]:
pd.DataFrame(fresh_basket).to_csv(filename, index=False)

LICENSE                             data_4_11_2024.csv
README.md                           e-katanalotis.ipynb
data_1_11_2024.csv                  ekatanalotis
data_2_11_2024.csv                  fresh_basket_29_10_to_4_11_2024.csv
data_3_11_2024.csv                  script.py